/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KhoaHocIndexRouteImport } from './routes/khoa-hoc.index'
import { Route as KhoaHocSlugRouteImport } from './routes/khoa-hoc.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoaHocIndexRoute = KhoaHocIndexRouteImport.update({
  id: '/khoa-hoc/',
  path: '/khoa-hoc/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoaHocSlugRoute = KhoaHocSlugRouteImport.update({
  id: '/khoa-hoc/$slug',
  path: '/khoa-hoc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/khoa-hoc/': typeof KhoaHocIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/khoa-hoc': typeof KhoaHocIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/khoa-hoc/$slug': typeof KhoaHocSlugRoute
  '/khoa-hoc/': typeof KhoaHocIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/khoa-hoc/$slug' | '/khoa-hoc/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/khoa-hoc/$slug' | '/khoa-hoc'
  id: '__root__' | '/' | '/sitemap.xml' | '/khoa-hoc/$slug' | '/khoa-hoc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KhoaHocSlugRoute: typeof KhoaHocSlugRoute
  KhoaHocIndexRoute: typeof KhoaHocIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoa-hoc/': {
      id: '/khoa-hoc/'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc/'
      preLoaderRoute: typeof KhoaHocIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoa-hoc/$slug': {
      id: '/khoa-hoc/$slug'
      path: '/khoa-hoc/$slug'
      fullPath: '/khoa-hoc/$slug'
      preLoaderRoute: typeof KhoaHocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KhoaHocSlugRoute: KhoaHocSlugRoute,
  KhoaHocIndexRoute: KhoaHocIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
